### ISSUE TITLE
Abandon or rejuvenate?

### ISSUE THREAD

**Issue by obestwalter** [Avira/avira.github.com#1]
This was updated last 2014. We should either get rid of this or keep it current. Ideally all members of the organization should have ownership of this repo, so everybody can keep their stuff updated.

**Comment by drscream** [comment]
Every member of the Avira organisation is able to contribute to this repo now. Feel free to keep the stuff up-to-date. If there will be no changes in the upcoming days or month we will disable and remove the repository.

**Comment by obestwalter** [comment]
Thanks - sounds like a plan :)
