### ISSUE TITLE
Less teams, more simple

### ISSUE THREAD

**Issue by obestwalter** [Avira/avira.github.com#2]
The org has no issues, so I open this here.

We have 11 teams https://github.com/orgs/Avira/teams and some of them are definitely outdated. I would propose, we get rid of the teams except for a team that has extended admin rights for the org. If we need teams, then we should nest them and have on team with all members, like so: https://help.github.com/articles/about-teams/#nested-teams.

**Comment by drscream** [comment]
The team structure has been improved and cleaned. I hope everything makes it easier now :-)
